---
title: "Research"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#### Hjermitslev, Ida B. (2020) ["The electoral cost of coalition participation: Can anyone escape?"](http://journals.sagepub.com/doi/abs/10.1177/1354068818794216) *Party Politics* 26(4), 510-520

It is a well-established empirical finding that governments on average lose votes during their time in office. This exploratory analysis examines whether all members of coalition governments suffer the electoral cost of governing equally. Using electoral data from 20 parliamentary systems from 1961 to 2015, I compare the electoral performance of junior coalition members, the prime minister of a coalition, and single-party governments. Furthermore, I examine the conditioning effects of economic performance, legislative institutions as well as party ideology and size. I find that there are substantial differences in the electoral cost of governing for different types of coalition participation. The evidence suggests that the prime minister in a coalition is partially insulated from the penalties of government and thus should try to attract junior coalition members whenever possible.
  
  * [Data manipulation](files/ElectoralCostData.R)
  
  * [Empirical analysis](files/ElectoralCostAnalysis.R)
  
  
#### Hjermitslev, Ida B. (2022) ["Mainstream Sell-Outs? How Collaboration with the Radical Right Changes Perceptions of Party Positions on Immigration."](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/13EF565C0110FAAD42A64E67CA71762E/S0017257X20000287a.pdf/mainstream_sellouts_how_collaboration_with_the_radical_right_changes_perceptions_of_party_positions_on_immigration.pdf) *Government and Opposition: An International Journal of Comparative Politics* 57(1), 31-55

European mainstream right parties are increasingly choosing to include radical right parties in coalition governments or other types of stable and committed cooperation. How does this cooperation affect voters' perceptions of party positions? This article examines whether coalition signals have a significant impact on voters' perceptions on the specific policy issues that were at stake in the bargaining process. More specifically, does the issue ownership of the radical right cause voters to perceive mainstream parties as radicalizing on immigration issues pertaining to asylum and multiculturalism? I compare the perceptions of Dutch parties before and after two coalition formations that (formally and informally) involved a radical right party: the coalition with the List Pim Fortuyn in 2002 and the support agreement with the Freedom Party in 2010. Furthermore, I examine the long-term effects of the Danish mainstream right government's reliance on the support of the radical right Danish People's Party in 2001-2011.
  
   * [The Netherlands 2002-2003](files/Results2002NL.R)
  
 * [The Netherlands 2010-2012](files/Results2010NL.R)
 
 * [Denmark 1994-2015](files/ResultsDK.R)
  

#### Hjermitslev, Ida B. (2023) [“Collaboration or competition? Experimental evidence for coalition heuristics”.](https://ejpr.onlinelibrary.wiley.com/doi/pdfdirect/10.1111/1475-6765.12537) *European Journal of Political Research* 62 (1), 326-337

Does coalition formation have a causal effect on the perceived ideological distance between the coalition members? Observational research shows that voters typically think of parties that form a coalition government as more ideologically similar than those that do not, holding everything else constant. Their many qualities aside, the existing studies are not able to establish a causal relationship between coalition formation and changing perceptions. It is quite possible that voters are reacting to concurrent changes in parties' stated policy and not the coalition information itself. In this paper, I present two survey experiments that isolates the difference between telling voters that two parties can cooperate and telling them that they cannot. In both experiments, I find evidence supporting the theory of coalition heuristics.

  * [Survey Questionnaire](files/QuestionnaireDK2018.pdf)
  
 * [Survey data](files/Coalition Heuristics Denmark 2018 Final.csv)
 
 * [Drake file](files/DrakeDK2018.R)
 
 * [Data manipulation](files/CleanDK2018.R)
 
 * [Empirical analysis](files/ResultsDK2018.Rmd)
 
 * [Supplemental Appendix](files/ejpr12537-sup-0001-onlineappendix.pdf)
  
#### Hjermitslev, Ida B. (2022) [Between cabinet membership and opposition: Commitment and responsibility of support parties](https://journals.sagepub.com/doi/pdf/10.1177/13540688221104557) *Party Politics*

Existing research suggests that government participation is crucial for how voters evaluate party performance and how they
cast their votes. However, in real life the distinction between government and opposition is not as straight-forward as one
would think. Minority governments often enjoy the legislative support of external support parties, which play an ambiguous
role in politics: while they are formally part of the opposition, they are simultaneously committed to keeping the government in office and passing its bills. How do voters evaluate parties that support a minority government? Will they
respond to different frames about the significance of the commitment that support parties have made to government policy
and survival? In a survey experiment, I test whether framing a written agreement as effective will cause voters to attribute
more or less responsibility to the support parties and find that they respond to different frames by altering their perceptions of the importance of the agreement, but not their responsibility attribution.

* [Survey Questionnaire](files/QuestionnaireDK2020.pdf)
* [Survey Data](files/MinGovData.dta)
* [Data Manipulation](files/CleanDataPP2022.R) 
* [Balance Test](files/BalancetestPP2022.R)
* [Empirical Analysis](files/ResultsPP2022.R)
* [Supplemental Appendix](files/pp_appendix.pdf)

#### Hjermitslev, Ida B. and Christopher D. Johnston (2022) [Mixed evidence for a relationship of cognitive fatigue to political engagement](https://journals.sagepub.com/doi/pdf/10.1177/13540688221104557) *Electoral Studies*

Daily cognitive fatigue is widespread, yet we are still learning about its influence on political behavior. Existing research suggests fatigue will reduce consumption of politics at the margin. Moreover, when fatigued individuals do engage with political material, they should be more likely to choose content and decision rules that require minimal effort. We find mixed empirical evidence for these claims. In observational data, we find a negative relationship between fatigue and engagement, on average, but the coefficients are typically small and statistically insignificant and we find substantial variation across different measures of fatigue. In three experiments, we find mixed evidence that manipulated fatigue reduces the demand for political content over sports and other non-political entertainment. In a fourth experiment, we find no evidence that manipulated fatigue shapes heuristic versus systematic processing. We discuss the limitations of our study, its relationship to existing work, and avenues for future research.

* [README](files/README.docx)
* [Data Folder](files/Data.zip)
* [Reproduction Folder](files/Reproduction.zip) 

#### Hjermitslev, Ida B. and Svenja Krauss (2023) Perceptual Consequences of Portfolios: How Allocation Affects Left-Right Placement *Government and Opposition*

Recent research suggests that party leaders can strategically impact the perceived left-right position of their parties by changing their selective emphasis on certain issues. We suggest that a party's ideological image can also be altered by the portfolio allocation of the coalition government the party participates in. By controlling a portfolio, the party will have a more direct influence on the related issue and will frequently communicate the party's issue position publicly thereby cultivating the equivalent to a perception of strong emphasis on the related issue. We run a cross-national party-level analysis showing that portfolio allocation matters with regard to the importance of the sub-dimensions for the general left-right dimension. In particular, the influence of socio-cultural stances depends on the share of socio-cultural portfolios. In addition, we show that the mechanism does not apply at the beginning of the governments tenure, but only after a year or longer in office.

* [Voter Perception Data](files/cheseesres.xlsx)
* [Portfolio Data](files/portfoliofullname.xlsx)
* [Italian Data](files/Citaly.xlsx) 
* [Data Manipulation](files/Merge_cheseesres_and_portfolio_FEB23.R)
* [Empirical Analysis](files/replication.do)
